// <auto-generated />
using System;
using Balaie_Cristian_Vlad_PROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Balaie_Cristian_Vlad_PROJECT.Migrations
{
    [DbContext(typeof(Balaie_Cristian_Vlad_PROJECTContext))]
    [Migration("20221209134337_Creation")]
    partial class Creation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Compound", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("MetalID")
                        .HasColumnType("int");

                    b.Property<int>("MetalQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MetalloidID")
                        .HasColumnType("int");

                    b.Property<int>("MetalloidQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NonMetalID")
                        .HasColumnType("int");

                    b.Property<int>("NonMetalQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MetalID");

                    b.HasIndex("MetalloidID");

                    b.HasIndex("NonMetalID");

                    b.ToTable("Compound");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Metal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("MetalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Valency")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Metal");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Metalloid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("MetalloidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Valency")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Metalloid");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.NonMetal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NonMetalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Valency")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("NonMetal");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Compound", b =>
                {
                    b.HasOne("Balaie_Cristian_Vlad_PROJECT.Models.Metal", "Metal")
                        .WithMany("Compounds")
                        .HasForeignKey("MetalID");

                    b.HasOne("Balaie_Cristian_Vlad_PROJECT.Models.Metalloid", "Metalloid")
                        .WithMany("Compounds")
                        .HasForeignKey("MetalloidID");

                    b.HasOne("Balaie_Cristian_Vlad_PROJECT.Models.NonMetal", "NonMetal")
                        .WithMany("Compounds")
                        .HasForeignKey("NonMetalID");

                    b.Navigation("Metal");

                    b.Navigation("Metalloid");

                    b.Navigation("NonMetal");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Metal", b =>
                {
                    b.Navigation("Compounds");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.Metalloid", b =>
                {
                    b.Navigation("Compounds");
                });

            modelBuilder.Entity("Balaie_Cristian_Vlad_PROJECT.Models.NonMetal", b =>
                {
                    b.Navigation("Compounds");
                });
#pragma warning restore 612, 618
        }
    }
}
